---
title: "Week 10 Lab"
subtitle: "Validating LiDAR tree height estimates"
format: html
---

## Set Up 
```{r}
library(tidyverse)
library(sf)
library(here)
library(terra)
library(stars)
library(gstat)
library(tmap)
library(kableExtra)
```

## Load LiDAR Data
```{r}
# digital surface model 
dsm <- rast(here("data", "SJER2013_DSM.tif"))

# digital terrian model 
dtm <- rast(here("data", "SJER2013_DTM.tif"))

# Stack the rasters 
test_raster <- c(dsm, dtm) # same resolution and extent 
```

## Create canopy height model 
```{r}
# Subtract one raster from the other
chm <- dsm - dtm
```

## Load vegetation plot geometries 
```{r}
plot_centroids <- st_read(here("data", "PlotCentroids", "SJERPlotCentroids_Buffer.shp")) %>% 
  st_transform(., crs = st_crs(chm))
```

```{r}
tm_shape(chm) +
  tm_raster(title = "Canopy height model (m)") +
  tm_shape(plot_centroids) +
  tm_polygons()
```


## Load vegetation survey data 
```{r}
veg_surveys <- read.csv(here("data", "VegetationData", "D17_2013_vegStr.csv")) %>% 
  group_by(plotid) %>% 
  summarize("survey_height" = max(stemheight, na.rm = TRUE))
```

```{r}
# Find heights from LiDAR data 
extract_chm_height <- terra::extract(chm, plot_centroids, fun = max) %>% 
  rename(chm_height = SJER2013_DSM) %>% 
  select(chm_height)

# Bind data from canopy height model and survey data 
plot_centroids <- cbind(plot_centroids, extract_chm_height) %>% 
  left_join(., veg_surveys, by = c("Plot_ID" = "plotid")) # When columns have different names 
```


```{r}
ggplot(plot_centroids, aes(x = chm_height, y= survey_height)) +
  geom_point() + 
  geom_smooth(method = lm) +
  geom_abline(slope = 1, intercept = 0, alpha = 0.5, lty = 2) +
  labs(x = "Maximum measured height (LiDAR)",
       y = "Maximum measured height (survey)", 
       title = "Validating Lidar measurements") +
  theme_minimal()
```



